name: telegram deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PATH_LOCAL: "bots/telegram"
    strategy:
      matrix:
        node-version: [16]
        npm-version: [7]
    if: "contains(github.event.head_commit.message, 'telegram:')"
    steps:
    - uses: actions/checkout@v2
    - name: Use node@${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use npm@${{ matrix.npm-version }}
      run: npm install -g npm@${{ matrix.npm-version }}
    - name: Install dependencies
      run: npm install
    - name: Bootstrap and Build application
      run: npm run build:telegram
    - name: Prepare artifact before cloud push
      run: |
        cp $PATH_LOCAL/package.production.json $PATH_LOCAL/dist/package.json
        cp $PATH_LOCAL/node_modules $PATH_LOCAL/dist/node_modules
        cp $PATH_LOCAL/Dockerfile $PATH_LOCAL/dist
    - name: Install CapRover
      run: npm install -g caprover
    - name: Zip aftifact into .tar file
      uses: thedoctor0/zip-release@master
      with:
        type: 'tar'
        filename: '../output.tar'
        directory: 'bots/telegram/dist/'
    - name: Push artifact to private Odzi Platform instance
      run: |
        cd bots/telegram
        caprover deploy -h https://captain.app.odzi.dog -p ${{ secrets.CAPROVER_PASSWORD }} --tarFile=output.tar -a leggydog-telegram-service
        